# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_uuid', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
                ('master_code', models.CharField(max_length=200, unique=True)),
                ('describe', models.CharField(max_length=900)),
                ('tel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QrLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_uuid', models.CharField(max_length=200, unique=True)),
                ('qrcode', models.CharField(max_length=200, unique=True)),
                ('data_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.DataMaster')),
            ],
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('json', models.CharField(default='', max_length=900)),
                ('city', models.CharField(default='', max_length=200)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('qr_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.QrLabel')),
            ],
        ),
    ]
