# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('qrcode', models.CharField(max_length=200)),
                ('scan_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(verbose_name='date scaned')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Qr')),
            ],
        ),
    ]
