# Generated by Django 2.0 on 2018-01-03 05:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_uuid', models.CharField(max_length=200, unique=True, verbose_name='管理码')),
                ('master_code', models.CharField(max_length=200, unique=True, verbose_name='管理码编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('title_show', models.BooleanField(default=True, verbose_name='是否显示标题')),
                ('company', models.CharField(default='太数智能科技（上海）有限公司', max_length=200, verbose_name='单位')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('distributor', models.CharField(blank=True, default='', max_length=200, verbose_name='经销商')),
                ('img_url', models.URLField(blank=True, verbose_name='主图地址')),
                ('redirect_url', models.CharField(default='http://tslink.cc', max_length=200, verbose_name='默认跳转地址')),
                ('redirect_url_wx', models.CharField(default='http://tslink.cc', max_length=200, verbose_name='跳转地址(微信客户端)')),
                ('redirect_url_jd', models.CharField(default='http://tslink.cc', max_length=200, verbose_name='跳转地址(京东客户端-无效)')),
                ('redirect_url_tb', models.CharField(default='http://tslink.cc', max_length=200, verbose_name='跳转地址(支付宝\\淘宝)')),
                ('redirect_on', models.BooleanField(default=False, verbose_name='是否跳转')),
                ('img_show', models.BooleanField(default=True, verbose_name='是否显示主图')),
                ('describe', models.TextField(blank=True, default='', max_length=900, verbose_name='文字描述')),
                ('scan_show', models.BooleanField(default=True, verbose_name='是否显示扫描结果')),
                ('describe_show', models.BooleanField(default=True, verbose_name='是否显示描述信息')),
                ('feedback_show', models.BooleanField(default=False, verbose_name='是否开启标签反馈模块')),
                ('tel', models.CharField(max_length=200, verbose_name='电话')),
                ('template', models.CharField(default='v1/qrscan.html', max_length=200, verbose_name='模版名称')),
                ('sales_on', models.BooleanField(default=False, verbose_name='售后码')),
            ],
            options={
                'verbose_name': '标签组',
                'verbose_name_plural': '2.标签组',
            },
        ),
        migrations.CreateModel(
            name='LabelFeedBack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed_back', models.TextField(default='无', verbose_name='反馈内容')),
                ('contact', models.CharField(default='无', max_length=200, verbose_name='联系方式')),
                ('user', models.CharField(default='', max_length=200, verbose_name='人员')),
                ('upload_img_url', models.URLField(blank=True, verbose_name='图片')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 3, 5, 40, 9, 189330), verbose_name='时间')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP')),
                ('handled', models.BooleanField(default=False, verbose_name='处理')),
            ],
            options={
                'verbose_name': '标签反馈',
                'verbose_name_plural': '4.标签反馈',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='LabelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_code', models.IntegerField(default=1, verbose_name='管理码编号')),
                ('label_code', models.IntegerField(default=1, verbose_name='粘贴码序号')),
            ],
            options={
                'verbose_name': '申请记录',
                'verbose_name_plural': '0.申请记录',
            },
        ),
        migrations.CreateModel(
            name='QrLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_uuid', models.CharField(max_length=200, unique=True, verbose_name='粘贴码')),
                ('label_code', models.CharField(max_length=200, verbose_name='粘贴码序号')),
                ('remark', models.CharField(default='-', max_length=200, verbose_name='备注')),
                ('qrcode', models.CharField(max_length=200, unique=True, verbose_name='粘贴码编号')),
                ('url', models.URLField(blank=True, verbose_name='URL地址')),
                ('has_sale', models.BooleanField(default=False, verbose_name='售出')),
                ('equip_no', models.CharField(default='', max_length=200, verbose_name='设备序列号')),
                ('equip_img_url', models.URLField(blank=True, verbose_name='图片地址')),
                ('mark_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 3, 5, 40, 9, 188250), verbose_name='标记时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '3.标签',
            },
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('json', models.CharField(default='', max_length=900)),
                ('city', models.CharField(default='', max_length=200, verbose_name='城市')),
                ('scan_date', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
                ('qr_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.QrLabel')),
            ],
            options={
                'verbose_name': '扫码记录',
                'verbose_name_plural': '5.扫码记录',
            },
        ),
        migrations.CreateModel(
            name='DMP',
            fields=[
                ('datamaster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.DataMaster')),
            ],
            options={
                'verbose_name': '标签组模版',
                'verbose_name_plural': '1.标签组模版',
            },
            bases=('v1.datamaster',),
        ),
        migrations.AddField(
            model_name='qrlabel',
            name='data_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.DataMaster'),
        ),
        migrations.AddField(
            model_name='labelfeedback',
            name='qr_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.QrLabel', verbose_name='标签'),
        ),
    ]
