# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=900)),
                ('tel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QrLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=200)),
                ('data_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.DataMaster')),
            ],
        ),
    ]
