# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_datamaster_qrlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamaster',
            name='master_code',
            field=models.CharField(default=123456, max_length=200),
            preserve_default=False,
        ),
    ]
