# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20171030_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scan',
            name='qr',
        ),
        migrations.AddField(
            model_name='datamaster',
            name='img_url',
            field=models.URLField(default='http://www.t3315.com/images/1-1F11QJ442912.png'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datamaster',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datamaster',
            name='master_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='qrlabel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrlabel',
            name='qrcode',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Qr',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='qr_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.QrLabel'),
        ),
    ]
