# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20171101_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
