# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_datamaster_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamaster',
            name='img',
        ),
    ]
