# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_remove_datamaster_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamaster',
            name='master_uuid',
            field=models.CharField(default='1231', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrlabel',
            name='label_uuid',
            field=models.CharField(default='12312', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
