# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_auto_20171106_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='json',
            field=models.CharField(default='', max_length=900),
        ),
    ]
